feature- add support for wiremock options as env variable - Resolves #78
wiremock/wiremock-docker pull request #90
Opened 2023-10-14 19:40 UTC by kapishmalik

This PR adds option to pass wiremock options as env variable to docker file and use it from helm chart.

## References
Resolves - https://github.com/wiremock/wiremock-docker/issues/78

## Submitter checklist

- [x] Recommended: Join [WireMock Slack](https://slack.wiremock.org/) to get any help in `#help-contributing` or a project-specific channel like `#wiremock-java`
- [x] Recommended: If you participate in Hacktoberfest 2023, make sure you're [signed up](https://wiremock.org/events/hacktoberfest/) there and in the WireMock form 
- [x] The PR request is well described and justified, including the body and the references
- [x] The PR title represents the desired changelog entry
- [x] The repository's code style is followed (see the contributing guide)
- [ ] For new features, there's necessary documentation in this pull request or in a subsequent PR to [wiremock.org](https://github.com/wiremock/wiremock.org)

2023-10-15 08:49 UTC, oleg-nenashev requested changes
Thanks for starting it! The alpine image needs to be updated too. Please also add an integration tests

2023-10-15 18:11 UTC, kapishmalik commented
@oleg-nenashev  no change is required on alpine as I have done change at common script docker-entrypoint.sh which is being invoked in both Dockerfiles. Also, integration test written are using testcontainer. Is there any mechanism to set environment variables.

2023-10-15 18:49 UTC, oleg-nenashev commented
There is another entry point for alpine https://github.com/wiremock/wiremock-docker/blob/main/alpine/docker-entrypoint.sh

2023-10-15 18:51 UTC, oleg-nenashev commented
And yes, there is a `GenericContainer#withEnv()` method

2023-10-15 21:09 UTC, kapishmalik commented
@oleg-nenashev incorporated review comment changes.

2023-10-16 05:08 UTC, oleg-nenashev approved these changes
Thanks for the patch! All good, will release it shortly

2023-10-16 05:08 UTC, merged